services:
  avaluoapi:
    image: ${DOCKER_REGISTRY-}avaluoapi
    build:
      context: .
      dockerfile: AvaluoAPI/Dockerfile
    ports:
      - 8001:443
    depends_on:
      - redis
    
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always

volumes:
  redis-data: